name: Python application CI/CD

# Déclenchez ce workflow lorsque des modifications sont poussées ou des pull requests sont créées sur la branche "main".
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Git LFS
      run: |
        # Install Git LFS
        sudo apt-get install git-lfs
        # Initialize Git LFS in the repository
        git lfs install

    - name: Checkout source code with Git LFS
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Configuration de Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Installation des dépendances Python
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint avec flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test avec pytest
      run: |
        pytest

    - name: Déploiement vers EC2
      run: |
        # Utilisation de la clé privée SSH depuis le secret
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > my_private_key.pem

        # Copie des fichiers vers l'instance EC2 (exemple)
        scp -i my_private_key.pem -r ./myapp ${{ secrets.EC2_USER }}@${{ secrets.HOST }}:${{ secrets.EC2_TARGET_PATH }}

        # Exécution de commandes de déploiement (exemple)
        ssh -i my_private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.HOST }} "cd ${{ secrets.EC2_TARGET_PATH }} && ./deploy.sh"
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock

# Fin du fichier YAML
