name: Python application CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Installation de Git LFS
      run: |
        # Installez Git LFS
        sudo apt-get install git-lfs
        # Initialisez Git LFS dans le référentiel
        git lfs install

    - name: Checkout du code source
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Configuration de Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Installation des dépendances Python
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint avec flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test avec pytest
      run: |
        pytest

    - name: Utilisation de la clé privée SSH depuis le secret
      run: echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > id_rsa

    - name: Copie des fichiers vers l'instance EC2
      run: scp -i id_rsa -r ./myapp ${{ secrets.EC2_USER }}@${{ secrets.HOST }}:${{ secrets.EC2_TARGET_PATH }}

    - name: Exécution de commandes de déploiement
      run: ssh -i id_rsa ${{ secrets.EC2_USER }}@${{ secrets.HOST }} "cd ${{ secrets.EC2_TARGET_PATH }} && ./deploy.sh"
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
